[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host 0.0.0.0 --port $PORT"
